/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVisitorsRouteImport } from './routes/_authenticated/visitors'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedTelegramRouteImport } from './routes/_authenticated/telegram'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPmPlansRouteImport } from './routes/_authenticated/pm-plans'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedParkingRouteImport } from './routes/_authenticated/parking'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedIdentityRouteImport } from './routes/_authenticated/identity'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyReportRouteImport } from './routes/_authenticated/daily-report'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedBuildingMapRouteImport } from './routes/_authenticated/building-map'
import { Route as AuthenticatedBuildingLogRouteImport } from './routes/_authenticated/building-log'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedApiDocsRouteImport } from './routes/_authenticated/api-docs'
import { Route as AuthenticatedOfficesIndexRouteImport } from './routes/_authenticated/offices.index'
import { Route as AuthenticatedVendorsIdRouteImport } from './routes/_authenticated/vendors.$id'
import { Route as AuthenticatedTenantsIdRouteImport } from './routes/_authenticated/tenants.$id'
import { Route as AuthenticatedOfficesIdRouteImport } from './routes/_authenticated/offices.$id'
import { Route as AuthenticatedContractsIdRouteImport } from './routes/_authenticated/contracts.$id'
import { Route as AuthenticatedComplaintsIdRouteImport } from './routes/_authenticated/complaints.$id'
import { Route as AuthenticatedAssetsIdRouteImport } from './routes/_authenticated/assets.$id'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1/$'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramNotifyRouteImport } from './routes/api/public/telegram/notify'
import { Route as ApiPublicTelegramDailyReportRouteImport } from './routes/api/public/telegram/daily-report'
import { Route as AuthenticatedSecurityGuardsIdRouteImport } from './routes/_authenticated/security.guards.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisitorsRoute = AuthenticatedVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTelegramRoute = AuthenticatedTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPmPlansRoute = AuthenticatedPmPlansRouteImport.update({
  id: '/pm-plans',
  path: '/pm-plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParkingRoute = AuthenticatedParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdentityRoute = AuthenticatedIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyReportRoute =
  AuthenticatedDailyReportRouteImport.update({
    id: '/daily-report',
    path: '/daily-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuildingMapRoute =
  AuthenticatedBuildingMapRouteImport.update({
    id: '/building-map',
    path: '/building-map',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildingLogRoute =
  AuthenticatedBuildingLogRouteImport.update({
    id: '/building-log',
    path: '/building-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiDocsRoute = AuthenticatedApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficesIndexRoute =
  AuthenticatedOfficesIndexRouteImport.update({
    id: '/offices/',
    path: '/offices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsIdRoute = AuthenticatedVendorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedVendorsRoute,
} as any)
const AuthenticatedTenantsIdRoute = AuthenticatedTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTenantsRoute,
} as any)
const AuthenticatedOfficesIdRoute = AuthenticatedOfficesIdRouteImport.update({
  id: '/offices/$id',
  path: '/offices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractsIdRoute =
  AuthenticatedContractsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedContractsRoute,
  } as any)
const AuthenticatedComplaintsIdRoute =
  AuthenticatedComplaintsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedComplaintsRoute,
  } as any)
const AuthenticatedAssetsIdRoute = AuthenticatedAssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAssetsRoute,
} as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramNotifyRoute = ApiPublicTelegramNotifyRouteImport.update({
  id: '/api/public/telegram/notify',
  path: '/api/public/telegram/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramDailyReportRoute =
  ApiPublicTelegramDailyReportRouteImport.update({
    id: '/api/public/telegram/daily-report',
    path: '/api/public/telegram/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSecurityGuardsIdRoute =
  AuthenticatedSecurityGuardsIdRouteImport.update({
    id: '/guards/$id',
    path: '/guards/$id',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/assets': typeof AuthenticatedAssetsRouteWithChildren
  '/building-log': typeof AuthenticatedBuildingLogRoute
  '/building-map': typeof AuthenticatedBuildingMapRoute
  '/complaints': typeof AuthenticatedComplaintsRouteWithChildren
  '/contracts': typeof AuthenticatedContractsRouteWithChildren
  '/daily-report': typeof AuthenticatedDailyReportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/parking': typeof AuthenticatedParkingRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/pm-plans': typeof AuthenticatedPmPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/security': typeof AuthenticatedSecurityRouteWithChildren
  '/telegram': typeof AuthenticatedTelegramRoute
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/vendors': typeof AuthenticatedVendorsRouteWithChildren
  '/visitors': typeof AuthenticatedVisitorsRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/offices/$id': typeof AuthenticatedOfficesIdRoute
  '/tenants/$id': typeof AuthenticatedTenantsIdRoute
  '/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/offices/': typeof AuthenticatedOfficesIndexRoute
  '/security/guards/$id': typeof AuthenticatedSecurityGuardsIdRoute
  '/api/public/telegram/daily-report': typeof ApiPublicTelegramDailyReportRoute
  '/api/public/telegram/notify': typeof ApiPublicTelegramNotifyRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/assets': typeof AuthenticatedAssetsRouteWithChildren
  '/building-log': typeof AuthenticatedBuildingLogRoute
  '/building-map': typeof AuthenticatedBuildingMapRoute
  '/complaints': typeof AuthenticatedComplaintsRouteWithChildren
  '/contracts': typeof AuthenticatedContractsRouteWithChildren
  '/daily-report': typeof AuthenticatedDailyReportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/parking': typeof AuthenticatedParkingRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/pm-plans': typeof AuthenticatedPmPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/security': typeof AuthenticatedSecurityRouteWithChildren
  '/telegram': typeof AuthenticatedTelegramRoute
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/vendors': typeof AuthenticatedVendorsRouteWithChildren
  '/visitors': typeof AuthenticatedVisitorsRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/offices/$id': typeof AuthenticatedOfficesIdRoute
  '/tenants/$id': typeof AuthenticatedTenantsIdRoute
  '/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/offices': typeof AuthenticatedOfficesIndexRoute
  '/security/guards/$id': typeof AuthenticatedSecurityGuardsIdRoute
  '/api/public/telegram/daily-report': typeof ApiPublicTelegramDailyReportRoute
  '/api/public/telegram/notify': typeof ApiPublicTelegramNotifyRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/api-docs': typeof AuthenticatedApiDocsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRouteWithChildren
  '/_authenticated/building-log': typeof AuthenticatedBuildingLogRoute
  '/_authenticated/building-map': typeof AuthenticatedBuildingMapRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRouteWithChildren
  '/_authenticated/contracts': typeof AuthenticatedContractsRouteWithChildren
  '/_authenticated/daily-report': typeof AuthenticatedDailyReportRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/identity': typeof AuthenticatedIdentityRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/parking': typeof AuthenticatedParkingRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/pm-plans': typeof AuthenticatedPmPlansRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRouteWithChildren
  '/_authenticated/telegram': typeof AuthenticatedTelegramRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRouteWithChildren
  '/_authenticated/visitors': typeof AuthenticatedVisitorsRoute
  '/_authenticated/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/_authenticated/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/_authenticated/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/_authenticated/offices/$id': typeof AuthenticatedOfficesIdRoute
  '/_authenticated/tenants/$id': typeof AuthenticatedTenantsIdRoute
  '/_authenticated/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/_authenticated/offices/': typeof AuthenticatedOfficesIndexRoute
  '/_authenticated/security/guards/$id': typeof AuthenticatedSecurityGuardsIdRoute
  '/api/public/telegram/daily-report': typeof ApiPublicTelegramDailyReportRoute
  '/api/public/telegram/notify': typeof ApiPublicTelegramNotifyRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/api-docs'
    | '/assets'
    | '/building-log'
    | '/building-map'
    | '/complaints'
    | '/contracts'
    | '/daily-report'
    | '/dashboard'
    | '/documents'
    | '/expenses'
    | '/finance'
    | '/identity'
    | '/inspections'
    | '/maintenance'
    | '/operations'
    | '/parking'
    | '/permissions'
    | '/pm-plans'
    | '/profile'
    | '/roles'
    | '/security'
    | '/telegram'
    | '/tenants'
    | '/users'
    | '/vendors'
    | '/visitors'
    | '/assets/$id'
    | '/complaints/$id'
    | '/contracts/$id'
    | '/offices/$id'
    | '/tenants/$id'
    | '/vendors/$id'
    | '/offices/'
    | '/security/guards/$id'
    | '/api/public/telegram/daily-report'
    | '/api/public/telegram/notify'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/api-docs'
    | '/assets'
    | '/building-log'
    | '/building-map'
    | '/complaints'
    | '/contracts'
    | '/daily-report'
    | '/dashboard'
    | '/documents'
    | '/expenses'
    | '/finance'
    | '/identity'
    | '/inspections'
    | '/maintenance'
    | '/operations'
    | '/parking'
    | '/permissions'
    | '/pm-plans'
    | '/profile'
    | '/roles'
    | '/security'
    | '/telegram'
    | '/tenants'
    | '/users'
    | '/vendors'
    | '/visitors'
    | '/assets/$id'
    | '/complaints/$id'
    | '/contracts/$id'
    | '/offices/$id'
    | '/tenants/$id'
    | '/vendors/$id'
    | '/offices'
    | '/security/guards/$id'
    | '/api/public/telegram/daily-report'
    | '/api/public/telegram/notify'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/api-docs'
    | '/_authenticated/assets'
    | '/_authenticated/building-log'
    | '/_authenticated/building-map'
    | '/_authenticated/complaints'
    | '/_authenticated/contracts'
    | '/_authenticated/daily-report'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/expenses'
    | '/_authenticated/finance'
    | '/_authenticated/identity'
    | '/_authenticated/inspections'
    | '/_authenticated/maintenance'
    | '/_authenticated/operations'
    | '/_authenticated/parking'
    | '/_authenticated/permissions'
    | '/_authenticated/pm-plans'
    | '/_authenticated/profile'
    | '/_authenticated/roles'
    | '/_authenticated/security'
    | '/_authenticated/telegram'
    | '/_authenticated/tenants'
    | '/_authenticated/users'
    | '/_authenticated/vendors'
    | '/_authenticated/visitors'
    | '/_authenticated/assets/$id'
    | '/_authenticated/complaints/$id'
    | '/_authenticated/contracts/$id'
    | '/_authenticated/offices/$id'
    | '/_authenticated/tenants/$id'
    | '/_authenticated/vendors/$id'
    | '/_authenticated/offices/'
    | '/_authenticated/security/guards/$id'
    | '/api/public/telegram/daily-report'
    | '/api/public/telegram/notify'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicTelegramDailyReportRoute: typeof ApiPublicTelegramDailyReportRoute
  ApiPublicTelegramNotifyRoute: typeof ApiPublicTelegramNotifyRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visitors': {
      id: '/_authenticated/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AuthenticatedVisitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/telegram': {
      id: '/_authenticated/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof AuthenticatedTelegramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pm-plans': {
      id: '/_authenticated/pm-plans'
      path: '/pm-plans'
      fullPath: '/pm-plans'
      preLoaderRoute: typeof AuthenticatedPmPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parking': {
      id: '/_authenticated/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof AuthenticatedParkingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identity': {
      id: '/_authenticated/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof AuthenticatedIdentityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-report': {
      id: '/_authenticated/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof AuthenticatedDailyReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/building-map': {
      id: '/_authenticated/building-map'
      path: '/building-map'
      fullPath: '/building-map'
      preLoaderRoute: typeof AuthenticatedBuildingMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/building-log': {
      id: '/_authenticated/building-log'
      path: '/building-log'
      fullPath: '/building-log'
      preLoaderRoute: typeof AuthenticatedBuildingLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-docs': {
      id: '/_authenticated/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AuthenticatedApiDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offices/': {
      id: '/_authenticated/offices/'
      path: '/offices'
      fullPath: '/offices/'
      preLoaderRoute: typeof AuthenticatedOfficesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/$id': {
      id: '/_authenticated/vendors/$id'
      path: '/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof AuthenticatedVendorsIdRouteImport
      parentRoute: typeof AuthenticatedVendorsRoute
    }
    '/_authenticated/tenants/$id': {
      id: '/_authenticated/tenants/$id'
      path: '/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof AuthenticatedTenantsIdRouteImport
      parentRoute: typeof AuthenticatedTenantsRoute
    }
    '/_authenticated/offices/$id': {
      id: '/_authenticated/offices/$id'
      path: '/offices/$id'
      fullPath: '/offices/$id'
      preLoaderRoute: typeof AuthenticatedOfficesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/$id': {
      id: '/_authenticated/contracts/$id'
      path: '/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof AuthenticatedContractsIdRouteImport
      parentRoute: typeof AuthenticatedContractsRoute
    }
    '/_authenticated/complaints/$id': {
      id: '/_authenticated/complaints/$id'
      path: '/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AuthenticatedComplaintsIdRouteImport
      parentRoute: typeof AuthenticatedComplaintsRoute
    }
    '/_authenticated/assets/$id': {
      id: '/_authenticated/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsIdRouteImport
      parentRoute: typeof AuthenticatedAssetsRoute
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/notify': {
      id: '/api/public/telegram/notify'
      path: '/api/public/telegram/notify'
      fullPath: '/api/public/telegram/notify'
      preLoaderRoute: typeof ApiPublicTelegramNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/daily-report': {
      id: '/api/public/telegram/daily-report'
      path: '/api/public/telegram/daily-report'
      fullPath: '/api/public/telegram/daily-report'
      preLoaderRoute: typeof ApiPublicTelegramDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/security/guards/$id': {
      id: '/_authenticated/security/guards/$id'
      path: '/guards/$id'
      fullPath: '/security/guards/$id'
      preLoaderRoute: typeof AuthenticatedSecurityGuardsIdRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
  }
}

interface AuthenticatedAssetsRouteChildren {
  AuthenticatedAssetsIdRoute: typeof AuthenticatedAssetsIdRoute
}

const AuthenticatedAssetsRouteChildren: AuthenticatedAssetsRouteChildren = {
  AuthenticatedAssetsIdRoute: AuthenticatedAssetsIdRoute,
}

const AuthenticatedAssetsRouteWithChildren =
  AuthenticatedAssetsRoute._addFileChildren(AuthenticatedAssetsRouteChildren)

interface AuthenticatedComplaintsRouteChildren {
  AuthenticatedComplaintsIdRoute: typeof AuthenticatedComplaintsIdRoute
}

const AuthenticatedComplaintsRouteChildren: AuthenticatedComplaintsRouteChildren =
  {
    AuthenticatedComplaintsIdRoute: AuthenticatedComplaintsIdRoute,
  }

const AuthenticatedComplaintsRouteWithChildren =
  AuthenticatedComplaintsRoute._addFileChildren(
    AuthenticatedComplaintsRouteChildren,
  )

interface AuthenticatedContractsRouteChildren {
  AuthenticatedContractsIdRoute: typeof AuthenticatedContractsIdRoute
}

const AuthenticatedContractsRouteChildren: AuthenticatedContractsRouteChildren =
  {
    AuthenticatedContractsIdRoute: AuthenticatedContractsIdRoute,
  }

const AuthenticatedContractsRouteWithChildren =
  AuthenticatedContractsRoute._addFileChildren(
    AuthenticatedContractsRouteChildren,
  )

interface AuthenticatedSecurityRouteChildren {
  AuthenticatedSecurityGuardsIdRoute: typeof AuthenticatedSecurityGuardsIdRoute
}

const AuthenticatedSecurityRouteChildren: AuthenticatedSecurityRouteChildren = {
  AuthenticatedSecurityGuardsIdRoute: AuthenticatedSecurityGuardsIdRoute,
}

const AuthenticatedSecurityRouteWithChildren =
  AuthenticatedSecurityRoute._addFileChildren(
    AuthenticatedSecurityRouteChildren,
  )

interface AuthenticatedTenantsRouteChildren {
  AuthenticatedTenantsIdRoute: typeof AuthenticatedTenantsIdRoute
}

const AuthenticatedTenantsRouteChildren: AuthenticatedTenantsRouteChildren = {
  AuthenticatedTenantsIdRoute: AuthenticatedTenantsIdRoute,
}

const AuthenticatedTenantsRouteWithChildren =
  AuthenticatedTenantsRoute._addFileChildren(AuthenticatedTenantsRouteChildren)

interface AuthenticatedVendorsRouteChildren {
  AuthenticatedVendorsIdRoute: typeof AuthenticatedVendorsIdRoute
}

const AuthenticatedVendorsRouteChildren: AuthenticatedVendorsRouteChildren = {
  AuthenticatedVendorsIdRoute: AuthenticatedVendorsIdRoute,
}

const AuthenticatedVendorsRouteWithChildren =
  AuthenticatedVendorsRoute._addFileChildren(AuthenticatedVendorsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiDocsRoute: typeof AuthenticatedApiDocsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRouteWithChildren
  AuthenticatedBuildingLogRoute: typeof AuthenticatedBuildingLogRoute
  AuthenticatedBuildingMapRoute: typeof AuthenticatedBuildingMapRoute
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRouteWithChildren
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRouteWithChildren
  AuthenticatedDailyReportRoute: typeof AuthenticatedDailyReportRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedIdentityRoute: typeof AuthenticatedIdentityRoute
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedParkingRoute: typeof AuthenticatedParkingRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedPmPlansRoute: typeof AuthenticatedPmPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRouteWithChildren
  AuthenticatedTelegramRoute: typeof AuthenticatedTelegramRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRouteWithChildren
  AuthenticatedVisitorsRoute: typeof AuthenticatedVisitorsRoute
  AuthenticatedOfficesIdRoute: typeof AuthenticatedOfficesIdRoute
  AuthenticatedOfficesIndexRoute: typeof AuthenticatedOfficesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiDocsRoute: AuthenticatedApiDocsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRouteWithChildren,
  AuthenticatedBuildingLogRoute: AuthenticatedBuildingLogRoute,
  AuthenticatedBuildingMapRoute: AuthenticatedBuildingMapRoute,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRouteWithChildren,
  AuthenticatedContractsRoute: AuthenticatedContractsRouteWithChildren,
  AuthenticatedDailyReportRoute: AuthenticatedDailyReportRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedIdentityRoute: AuthenticatedIdentityRoute,
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedParkingRoute: AuthenticatedParkingRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedPmPlansRoute: AuthenticatedPmPlansRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRouteWithChildren,
  AuthenticatedTelegramRoute: AuthenticatedTelegramRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRouteWithChildren,
  AuthenticatedVisitorsRoute: AuthenticatedVisitorsRoute,
  AuthenticatedOfficesIdRoute: AuthenticatedOfficesIdRoute,
  AuthenticatedOfficesIndexRoute: AuthenticatedOfficesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicTelegramDailyReportRoute: ApiPublicTelegramDailyReportRoute,
  ApiPublicTelegramNotifyRoute: ApiPublicTelegramNotifyRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
