/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LobbyCheckinRouteImport } from './routes/lobby-checkin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVisitorsRouteImport } from './routes/_authenticated/visitors'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedTelegramRouteImport } from './routes/_authenticated/telegram'
import { Route as AuthenticatedSupplyContractsRouteImport } from './routes/_authenticated/supply-contracts'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPmPlansRouteImport } from './routes/_authenticated/pm-plans'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedParkingRouteImport } from './routes/_authenticated/parking'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedLobbyRouteImport } from './routes/_authenticated/lobby'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedIdentityRouteImport } from './routes/_authenticated/identity'
import { Route as AuthenticatedFireContractsRouteImport } from './routes/_authenticated/fire-contracts'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedElevatorContractsRouteImport } from './routes/_authenticated/elevator-contracts'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyReportRouteImport } from './routes/_authenticated/daily-report'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedCommonAreasRouteImport } from './routes/_authenticated/common-areas'
import { Route as AuthenticatedCleaningContractsRouteImport } from './routes/_authenticated/cleaning-contracts'
import { Route as AuthenticatedBuildingMapRouteImport } from './routes/_authenticated/building-map'
import { Route as AuthenticatedBuildingLogRouteImport } from './routes/_authenticated/building-log'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedApiDocsRouteImport } from './routes/_authenticated/api-docs'
import { Route as AuthenticatedAcContractsRouteImport } from './routes/_authenticated/ac-contracts'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated/vendors.index'
import { Route as AuthenticatedOfficesIndexRouteImport } from './routes/_authenticated/offices.index'
import { Route as AuthenticatedEmployeesIndexRouteImport } from './routes/_authenticated/employees.index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts.index'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets.index'
import { Route as AuthenticatedVendorsIdRouteImport } from './routes/_authenticated/vendors.$id'
import { Route as AuthenticatedTenantsIdRouteImport } from './routes/_authenticated/tenants.$id'
import { Route as AuthenticatedOfficesIdRouteImport } from './routes/_authenticated/offices.$id'
import { Route as AuthenticatedEmployeesIdRouteImport } from './routes/_authenticated/employees.$id'
import { Route as AuthenticatedContractsIdRouteImport } from './routes/_authenticated/contracts.$id'
import { Route as AuthenticatedComplaintsIdRouteImport } from './routes/_authenticated/complaints.$id'
import { Route as AuthenticatedAssetsIdRouteImport } from './routes/_authenticated/assets.$id'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1/$'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramNotifyRouteImport } from './routes/api/public/telegram/notify'
import { Route as ApiPublicTelegramDailyReportRouteImport } from './routes/api/public/telegram/daily-report'
import { Route as AuthenticatedSecurityGuardsIdRouteImport } from './routes/_authenticated/security.guards.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyCheckinRoute = LobbyCheckinRouteImport.update({
  id: '/lobby-checkin',
  path: '/lobby-checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisitorsRoute = AuthenticatedVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTelegramRoute = AuthenticatedTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupplyContractsRoute =
  AuthenticatedSupplyContractsRouteImport.update({
    id: '/supply-contracts',
    path: '/supply-contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPmPlansRoute = AuthenticatedPmPlansRouteImport.update({
  id: '/pm-plans',
  path: '/pm-plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParkingRoute = AuthenticatedParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLobbyRoute = AuthenticatedLobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdentityRoute = AuthenticatedIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFireContractsRoute =
  AuthenticatedFireContractsRouteImport.update({
    id: '/fire-contracts',
    path: '/fire-contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedElevatorContractsRoute =
  AuthenticatedElevatorContractsRouteImport.update({
    id: '/elevator-contracts',
    path: '/elevator-contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyReportRoute =
  AuthenticatedDailyReportRouteImport.update({
    id: '/daily-report',
    path: '/daily-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommonAreasRoute =
  AuthenticatedCommonAreasRouteImport.update({
    id: '/common-areas',
    path: '/common-areas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCleaningContractsRoute =
  AuthenticatedCleaningContractsRouteImport.update({
    id: '/cleaning-contracts',
    path: '/cleaning-contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildingMapRoute =
  AuthenticatedBuildingMapRouteImport.update({
    id: '/building-map',
    path: '/building-map',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildingLogRoute =
  AuthenticatedBuildingLogRouteImport.update({
    id: '/building-log',
    path: '/building-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiDocsRoute = AuthenticatedApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcContractsRoute =
  AuthenticatedAcContractsRouteImport.update({
    id: '/ac-contracts',
    path: '/ac-contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficesIndexRoute =
  AuthenticatedOfficesIndexRouteImport.update({
    id: '/offices/',
    path: '/offices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesIndexRoute =
  AuthenticatedEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsIdRoute = AuthenticatedVendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsIdRoute = AuthenticatedTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTenantsRoute,
} as any)
const AuthenticatedOfficesIdRoute = AuthenticatedOfficesIdRouteImport.update({
  id: '/offices/$id',
  path: '/offices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesIdRoute =
  AuthenticatedEmployeesIdRouteImport.update({
    id: '/employees/$id',
    path: '/employees/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIdRoute =
  AuthenticatedContractsIdRouteImport.update({
    id: '/contracts/$id',
    path: '/contracts/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplaintsIdRoute =
  AuthenticatedComplaintsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedComplaintsRoute,
  } as any)
const AuthenticatedAssetsIdRoute = AuthenticatedAssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramNotifyRoute = ApiPublicTelegramNotifyRouteImport.update({
  id: '/api/public/telegram/notify',
  path: '/api/public/telegram/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramDailyReportRoute =
  ApiPublicTelegramDailyReportRouteImport.update({
    id: '/api/public/telegram/daily-report',
    path: '/api/public/telegram/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSecurityGuardsIdRoute =
  AuthenticatedSecurityGuardsIdRouteImport.update({
    id: '/guards/$id',
    path: '/guards/$id',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lobby-checkin': typeof LobbyCheckinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ac-contracts': typeof AuthenticatedAcContractsRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/building-log': typeof AuthenticatedBuildingLogRoute
  '/building-map': typeof AuthenticatedBuildingMapRoute
  '/cleaning-contracts': typeof AuthenticatedCleaningContractsRoute
  '/common-areas': typeof AuthenticatedCommonAreasRoute
  '/complaints': typeof AuthenticatedComplaintsRouteWithChildren
  '/daily-report': typeof AuthenticatedDailyReportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/elevator-contracts': typeof AuthenticatedElevatorContractsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/fire-contracts': typeof AuthenticatedFireContractsRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/lobby': typeof AuthenticatedLobbyRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/parking': typeof AuthenticatedParkingRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/pm-plans': typeof AuthenticatedPmPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/security': typeof AuthenticatedSecurityRouteWithChildren
  '/supply-contracts': typeof AuthenticatedSupplyContractsRoute
  '/telegram': typeof AuthenticatedTelegramRoute
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/visitors': typeof AuthenticatedVisitorsRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/offices/$id': typeof AuthenticatedOfficesIdRoute
  '/tenants/$id': typeof AuthenticatedTenantsIdRoute
  '/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/offices/': typeof AuthenticatedOfficesIndexRoute
  '/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/security/guards/$id': typeof AuthenticatedSecurityGuardsIdRoute
  '/api/public/telegram/daily-report': typeof ApiPublicTelegramDailyReportRoute
  '/api/public/telegram/notify': typeof ApiPublicTelegramNotifyRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lobby-checkin': typeof LobbyCheckinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ac-contracts': typeof AuthenticatedAcContractsRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/building-log': typeof AuthenticatedBuildingLogRoute
  '/building-map': typeof AuthenticatedBuildingMapRoute
  '/cleaning-contracts': typeof AuthenticatedCleaningContractsRoute
  '/common-areas': typeof AuthenticatedCommonAreasRoute
  '/complaints': typeof AuthenticatedComplaintsRouteWithChildren
  '/daily-report': typeof AuthenticatedDailyReportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/elevator-contracts': typeof AuthenticatedElevatorContractsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/fire-contracts': typeof AuthenticatedFireContractsRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/lobby': typeof AuthenticatedLobbyRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/parking': typeof AuthenticatedParkingRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/pm-plans': typeof AuthenticatedPmPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/security': typeof AuthenticatedSecurityRouteWithChildren
  '/supply-contracts': typeof AuthenticatedSupplyContractsRoute
  '/telegram': typeof AuthenticatedTelegramRoute
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/visitors': typeof AuthenticatedVisitorsRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/offices/$id': typeof AuthenticatedOfficesIdRoute
  '/tenants/$id': typeof AuthenticatedTenantsIdRoute
  '/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/offices': typeof AuthenticatedOfficesIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/security/guards/$id': typeof AuthenticatedSecurityGuardsIdRoute
  '/api/public/telegram/daily-report': typeof ApiPublicTelegramDailyReportRoute
  '/api/public/telegram/notify': typeof ApiPublicTelegramNotifyRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lobby-checkin': typeof LobbyCheckinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ac-contracts': typeof AuthenticatedAcContractsRoute
  '/_authenticated/api-docs': typeof AuthenticatedApiDocsRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/building-log': typeof AuthenticatedBuildingLogRoute
  '/_authenticated/building-map': typeof AuthenticatedBuildingMapRoute
  '/_authenticated/cleaning-contracts': typeof AuthenticatedCleaningContractsRoute
  '/_authenticated/common-areas': typeof AuthenticatedCommonAreasRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRouteWithChildren
  '/_authenticated/daily-report': typeof AuthenticatedDailyReportRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/elevator-contracts': typeof AuthenticatedElevatorContractsRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/fire-contracts': typeof AuthenticatedFireContractsRoute
  '/_authenticated/identity': typeof AuthenticatedIdentityRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRoute
  '/_authenticated/lobby': typeof AuthenticatedLobbyRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/parking': typeof AuthenticatedParkingRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/pm-plans': typeof AuthenticatedPmPlansRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRouteWithChildren
  '/_authenticated/supply-contracts': typeof AuthenticatedSupplyContractsRoute
  '/_authenticated/telegram': typeof AuthenticatedTelegramRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/visitors': typeof AuthenticatedVisitorsRoute
  '/_authenticated/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/_authenticated/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/_authenticated/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/_authenticated/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/_authenticated/offices/$id': typeof AuthenticatedOfficesIdRoute
  '/_authenticated/tenants/$id': typeof AuthenticatedTenantsIdRoute
  '/_authenticated/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/_authenticated/offices/': typeof AuthenticatedOfficesIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/_authenticated/security/guards/$id': typeof AuthenticatedSecurityGuardsIdRoute
  '/api/public/telegram/daily-report': typeof ApiPublicTelegramDailyReportRoute
  '/api/public/telegram/notify': typeof ApiPublicTelegramNotifyRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/lobby-checkin'
    | '/reset-password'
    | '/ac-contracts'
    | '/api-docs'
    | '/archive'
    | '/audit-log'
    | '/building-log'
    | '/building-map'
    | '/cleaning-contracts'
    | '/common-areas'
    | '/complaints'
    | '/daily-report'
    | '/dashboard'
    | '/documents'
    | '/elevator-contracts'
    | '/expenses'
    | '/finance'
    | '/fire-contracts'
    | '/identity'
    | '/inspections'
    | '/lobby'
    | '/maintenance'
    | '/notifications'
    | '/operations'
    | '/parking'
    | '/permissions'
    | '/pm-plans'
    | '/profile'
    | '/properties'
    | '/roles'
    | '/security'
    | '/supply-contracts'
    | '/telegram'
    | '/tenants'
    | '/users'
    | '/visitors'
    | '/assets/$id'
    | '/complaints/$id'
    | '/contracts/$id'
    | '/employees/$id'
    | '/offices/$id'
    | '/tenants/$id'
    | '/vendors/$id'
    | '/assets/'
    | '/contracts/'
    | '/employees/'
    | '/offices/'
    | '/vendors/'
    | '/security/guards/$id'
    | '/api/public/telegram/daily-report'
    | '/api/public/telegram/notify'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/lobby-checkin'
    | '/reset-password'
    | '/ac-contracts'
    | '/api-docs'
    | '/archive'
    | '/audit-log'
    | '/building-log'
    | '/building-map'
    | '/cleaning-contracts'
    | '/common-areas'
    | '/complaints'
    | '/daily-report'
    | '/dashboard'
    | '/documents'
    | '/elevator-contracts'
    | '/expenses'
    | '/finance'
    | '/fire-contracts'
    | '/identity'
    | '/inspections'
    | '/lobby'
    | '/maintenance'
    | '/notifications'
    | '/operations'
    | '/parking'
    | '/permissions'
    | '/pm-plans'
    | '/profile'
    | '/properties'
    | '/roles'
    | '/security'
    | '/supply-contracts'
    | '/telegram'
    | '/tenants'
    | '/users'
    | '/visitors'
    | '/assets/$id'
    | '/complaints/$id'
    | '/contracts/$id'
    | '/employees/$id'
    | '/offices/$id'
    | '/tenants/$id'
    | '/vendors/$id'
    | '/assets'
    | '/contracts'
    | '/employees'
    | '/offices'
    | '/vendors'
    | '/security/guards/$id'
    | '/api/public/telegram/daily-report'
    | '/api/public/telegram/notify'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/lobby-checkin'
    | '/reset-password'
    | '/_authenticated/ac-contracts'
    | '/_authenticated/api-docs'
    | '/_authenticated/archive'
    | '/_authenticated/audit-log'
    | '/_authenticated/building-log'
    | '/_authenticated/building-map'
    | '/_authenticated/cleaning-contracts'
    | '/_authenticated/common-areas'
    | '/_authenticated/complaints'
    | '/_authenticated/daily-report'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/elevator-contracts'
    | '/_authenticated/expenses'
    | '/_authenticated/finance'
    | '/_authenticated/fire-contracts'
    | '/_authenticated/identity'
    | '/_authenticated/inspections'
    | '/_authenticated/lobby'
    | '/_authenticated/maintenance'
    | '/_authenticated/notifications'
    | '/_authenticated/operations'
    | '/_authenticated/parking'
    | '/_authenticated/permissions'
    | '/_authenticated/pm-plans'
    | '/_authenticated/profile'
    | '/_authenticated/properties'
    | '/_authenticated/roles'
    | '/_authenticated/security'
    | '/_authenticated/supply-contracts'
    | '/_authenticated/telegram'
    | '/_authenticated/tenants'
    | '/_authenticated/users'
    | '/_authenticated/visitors'
    | '/_authenticated/assets/$id'
    | '/_authenticated/complaints/$id'
    | '/_authenticated/contracts/$id'
    | '/_authenticated/employees/$id'
    | '/_authenticated/offices/$id'
    | '/_authenticated/tenants/$id'
    | '/_authenticated/vendors/$id'
    | '/_authenticated/assets/'
    | '/_authenticated/contracts/'
    | '/_authenticated/employees/'
    | '/_authenticated/offices/'
    | '/_authenticated/vendors/'
    | '/_authenticated/security/guards/$id'
    | '/api/public/telegram/daily-report'
    | '/api/public/telegram/notify'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LobbyCheckinRoute: typeof LobbyCheckinRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicTelegramDailyReportRoute: typeof ApiPublicTelegramDailyReportRoute
  ApiPublicTelegramNotifyRoute: typeof ApiPublicTelegramNotifyRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby-checkin': {
      id: '/lobby-checkin'
      path: '/lobby-checkin'
      fullPath: '/lobby-checkin'
      preLoaderRoute: typeof LobbyCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visitors': {
      id: '/_authenticated/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AuthenticatedVisitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/telegram': {
      id: '/_authenticated/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof AuthenticatedTelegramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supply-contracts': {
      id: '/_authenticated/supply-contracts'
      path: '/supply-contracts'
      fullPath: '/supply-contracts'
      preLoaderRoute: typeof AuthenticatedSupplyContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pm-plans': {
      id: '/_authenticated/pm-plans'
      path: '/pm-plans'
      fullPath: '/pm-plans'
      preLoaderRoute: typeof AuthenticatedPmPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parking': {
      id: '/_authenticated/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof AuthenticatedParkingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lobby': {
      id: '/_authenticated/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof AuthenticatedLobbyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identity': {
      id: '/_authenticated/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof AuthenticatedIdentityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fire-contracts': {
      id: '/_authenticated/fire-contracts'
      path: '/fire-contracts'
      fullPath: '/fire-contracts'
      preLoaderRoute: typeof AuthenticatedFireContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/elevator-contracts': {
      id: '/_authenticated/elevator-contracts'
      path: '/elevator-contracts'
      fullPath: '/elevator-contracts'
      preLoaderRoute: typeof AuthenticatedElevatorContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-report': {
      id: '/_authenticated/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof AuthenticatedDailyReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/common-areas': {
      id: '/_authenticated/common-areas'
      path: '/common-areas'
      fullPath: '/common-areas'
      preLoaderRoute: typeof AuthenticatedCommonAreasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cleaning-contracts': {
      id: '/_authenticated/cleaning-contracts'
      path: '/cleaning-contracts'
      fullPath: '/cleaning-contracts'
      preLoaderRoute: typeof AuthenticatedCleaningContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/building-map': {
      id: '/_authenticated/building-map'
      path: '/building-map'
      fullPath: '/building-map'
      preLoaderRoute: typeof AuthenticatedBuildingMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/building-log': {
      id: '/_authenticated/building-log'
      path: '/building-log'
      fullPath: '/building-log'
      preLoaderRoute: typeof AuthenticatedBuildingLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-docs': {
      id: '/_authenticated/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AuthenticatedApiDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ac-contracts': {
      id: '/_authenticated/ac-contracts'
      path: '/ac-contracts'
      fullPath: '/ac-contracts'
      preLoaderRoute: typeof AuthenticatedAcContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offices/': {
      id: '/_authenticated/offices/'
      path: '/offices'
      fullPath: '/offices/'
      preLoaderRoute: typeof AuthenticatedOfficesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees/': {
      id: '/_authenticated/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthenticatedEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/$id': {
      id: '/_authenticated/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof AuthenticatedVendorsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/$id': {
      id: '/_authenticated/tenants/$id'
      path: '/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof AuthenticatedTenantsIdRouteImport
      parentRoute: typeof AuthenticatedTenantsRoute
    }
    '/_authenticated/offices/$id': {
      id: '/_authenticated/offices/$id'
      path: '/offices/$id'
      fullPath: '/offices/$id'
      preLoaderRoute: typeof AuthenticatedOfficesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees/$id': {
      id: '/_authenticated/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AuthenticatedEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/$id': {
      id: '/_authenticated/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof AuthenticatedContractsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints/$id': {
      id: '/_authenticated/complaints/$id'
      path: '/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AuthenticatedComplaintsIdRouteImport
      parentRoute: typeof AuthenticatedComplaintsRoute
    }
    '/_authenticated/assets/$id': {
      id: '/_authenticated/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/notify': {
      id: '/api/public/telegram/notify'
      path: '/api/public/telegram/notify'
      fullPath: '/api/public/telegram/notify'
      preLoaderRoute: typeof ApiPublicTelegramNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/daily-report': {
      id: '/api/public/telegram/daily-report'
      path: '/api/public/telegram/daily-report'
      fullPath: '/api/public/telegram/daily-report'
      preLoaderRoute: typeof ApiPublicTelegramDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/security/guards/$id': {
      id: '/_authenticated/security/guards/$id'
      path: '/guards/$id'
      fullPath: '/security/guards/$id'
      preLoaderRoute: typeof AuthenticatedSecurityGuardsIdRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
  }
}

interface AuthenticatedComplaintsRouteChildren {
  AuthenticatedComplaintsIdRoute: typeof AuthenticatedComplaintsIdRoute
}

const AuthenticatedComplaintsRouteChildren: AuthenticatedComplaintsRouteChildren =
  {
    AuthenticatedComplaintsIdRoute: AuthenticatedComplaintsIdRoute,
  }

const AuthenticatedComplaintsRouteWithChildren =
  AuthenticatedComplaintsRoute._addFileChildren(
    AuthenticatedComplaintsRouteChildren,
  )

interface AuthenticatedSecurityRouteChildren {
  AuthenticatedSecurityGuardsIdRoute: typeof AuthenticatedSecurityGuardsIdRoute
}

const AuthenticatedSecurityRouteChildren: AuthenticatedSecurityRouteChildren = {
  AuthenticatedSecurityGuardsIdRoute: AuthenticatedSecurityGuardsIdRoute,
}

const AuthenticatedSecurityRouteWithChildren =
  AuthenticatedSecurityRoute._addFileChildren(
    AuthenticatedSecurityRouteChildren,
  )

interface AuthenticatedTenantsRouteChildren {
  AuthenticatedTenantsIdRoute: typeof AuthenticatedTenantsIdRoute
}

const AuthenticatedTenantsRouteChildren: AuthenticatedTenantsRouteChildren = {
  AuthenticatedTenantsIdRoute: AuthenticatedTenantsIdRoute,
}

const AuthenticatedTenantsRouteWithChildren =
  AuthenticatedTenantsRoute._addFileChildren(AuthenticatedTenantsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcContractsRoute: typeof AuthenticatedAcContractsRoute
  AuthenticatedApiDocsRoute: typeof AuthenticatedApiDocsRoute
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedBuildingLogRoute: typeof AuthenticatedBuildingLogRoute
  AuthenticatedBuildingMapRoute: typeof AuthenticatedBuildingMapRoute
  AuthenticatedCleaningContractsRoute: typeof AuthenticatedCleaningContractsRoute
  AuthenticatedCommonAreasRoute: typeof AuthenticatedCommonAreasRoute
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRouteWithChildren
  AuthenticatedDailyReportRoute: typeof AuthenticatedDailyReportRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedElevatorContractsRoute: typeof AuthenticatedElevatorContractsRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedFireContractsRoute: typeof AuthenticatedFireContractsRoute
  AuthenticatedIdentityRoute: typeof AuthenticatedIdentityRoute
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRoute
  AuthenticatedLobbyRoute: typeof AuthenticatedLobbyRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedParkingRoute: typeof AuthenticatedParkingRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedPmPlansRoute: typeof AuthenticatedPmPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRouteWithChildren
  AuthenticatedSupplyContractsRoute: typeof AuthenticatedSupplyContractsRoute
  AuthenticatedTelegramRoute: typeof AuthenticatedTelegramRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVisitorsRoute: typeof AuthenticatedVisitorsRoute
  AuthenticatedAssetsIdRoute: typeof AuthenticatedAssetsIdRoute
  AuthenticatedContractsIdRoute: typeof AuthenticatedContractsIdRoute
  AuthenticatedEmployeesIdRoute: typeof AuthenticatedEmployeesIdRoute
  AuthenticatedOfficesIdRoute: typeof AuthenticatedOfficesIdRoute
  AuthenticatedVendorsIdRoute: typeof AuthenticatedVendorsIdRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedEmployeesIndexRoute: typeof AuthenticatedEmployeesIndexRoute
  AuthenticatedOfficesIndexRoute: typeof AuthenticatedOfficesIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcContractsRoute: AuthenticatedAcContractsRoute,
  AuthenticatedApiDocsRoute: AuthenticatedApiDocsRoute,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedBuildingLogRoute: AuthenticatedBuildingLogRoute,
  AuthenticatedBuildingMapRoute: AuthenticatedBuildingMapRoute,
  AuthenticatedCleaningContractsRoute: AuthenticatedCleaningContractsRoute,
  AuthenticatedCommonAreasRoute: AuthenticatedCommonAreasRoute,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRouteWithChildren,
  AuthenticatedDailyReportRoute: AuthenticatedDailyReportRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedElevatorContractsRoute: AuthenticatedElevatorContractsRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedFireContractsRoute: AuthenticatedFireContractsRoute,
  AuthenticatedIdentityRoute: AuthenticatedIdentityRoute,
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRoute,
  AuthenticatedLobbyRoute: AuthenticatedLobbyRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedParkingRoute: AuthenticatedParkingRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedPmPlansRoute: AuthenticatedPmPlansRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRouteWithChildren,
  AuthenticatedSupplyContractsRoute: AuthenticatedSupplyContractsRoute,
  AuthenticatedTelegramRoute: AuthenticatedTelegramRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVisitorsRoute: AuthenticatedVisitorsRoute,
  AuthenticatedAssetsIdRoute: AuthenticatedAssetsIdRoute,
  AuthenticatedContractsIdRoute: AuthenticatedContractsIdRoute,
  AuthenticatedEmployeesIdRoute: AuthenticatedEmployeesIdRoute,
  AuthenticatedOfficesIdRoute: AuthenticatedOfficesIdRoute,
  AuthenticatedVendorsIdRoute: AuthenticatedVendorsIdRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedEmployeesIndexRoute: AuthenticatedEmployeesIndexRoute,
  AuthenticatedOfficesIndexRoute: AuthenticatedOfficesIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LobbyCheckinRoute: LobbyCheckinRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicTelegramDailyReportRoute: ApiPublicTelegramDailyReportRoute,
  ApiPublicTelegramNotifyRoute: ApiPublicTelegramNotifyRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
