/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedParkingRouteImport } from './routes/_authenticated/parking'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedOfficesRouteImport } from './routes/_authenticated/offices'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedBuildingLogRouteImport } from './routes/_authenticated/building-log'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParkingRoute = AuthenticatedParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficesRoute = AuthenticatedOfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuildingLogRoute =
  AuthenticatedBuildingLogRouteImport.update({
    id: '/building-log',
    path: '/building-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/building-log': typeof AuthenticatedBuildingLogRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/offices': typeof AuthenticatedOfficesRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/parking': typeof AuthenticatedParkingRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vendors': typeof AuthenticatedVendorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/building-log': typeof AuthenticatedBuildingLogRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/offices': typeof AuthenticatedOfficesRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/parking': typeof AuthenticatedParkingRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vendors': typeof AuthenticatedVendorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/building-log': typeof AuthenticatedBuildingLogRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRoute
  '/_authenticated/offices': typeof AuthenticatedOfficesRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/parking': typeof AuthenticatedParkingRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assets'
    | '/building-log'
    | '/complaints'
    | '/contracts'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/inspections'
    | '/offices'
    | '/operations'
    | '/parking'
    | '/security'
    | '/tenants'
    | '/users'
    | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assets'
    | '/building-log'
    | '/complaints'
    | '/contracts'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/inspections'
    | '/offices'
    | '/operations'
    | '/parking'
    | '/security'
    | '/tenants'
    | '/users'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assets'
    | '/_authenticated/building-log'
    | '/_authenticated/complaints'
    | '/_authenticated/contracts'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/finance'
    | '/_authenticated/inspections'
    | '/_authenticated/offices'
    | '/_authenticated/operations'
    | '/_authenticated/parking'
    | '/_authenticated/security'
    | '/_authenticated/tenants'
    | '/_authenticated/users'
    | '/_authenticated/vendors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parking': {
      id: '/_authenticated/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof AuthenticatedParkingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offices': {
      id: '/_authenticated/offices'
      path: '/offices'
      fullPath: '/offices'
      preLoaderRoute: typeof AuthenticatedOfficesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/building-log': {
      id: '/_authenticated/building-log'
      path: '/building-log'
      fullPath: '/building-log'
      preLoaderRoute: typeof AuthenticatedBuildingLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedBuildingLogRoute: typeof AuthenticatedBuildingLogRoute
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRoute
  AuthenticatedOfficesRoute: typeof AuthenticatedOfficesRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedParkingRoute: typeof AuthenticatedParkingRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedBuildingLogRoute: AuthenticatedBuildingLogRoute,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRoute,
  AuthenticatedOfficesRoute: AuthenticatedOfficesRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedParkingRoute: AuthenticatedParkingRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
